sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.6.0

before_install:
  - docker pull postgres:9.4
  - docker-compose up -d postgres
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose build

script:
  - docker-compose up test
